# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-myportfolio"
BBFILE_PATTERN_meta-myportfolio = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-myportfolio = "6"

LAYERDEPENDS_meta-myportfolio = "core"
LAYERSERIES_COMPAT_meta-myportfolio = "scarthgap"
